apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- aerospike-kubernetes-operator.clusterserviceversion.yaml

commonAnnotations:
  containerImage: controller:latest
  createdAt: 2026-01-14T05:42:42UTC
