name: Eviction Webhook ENV Test Suite

on:
  push:
    tags:
      - v*
    branches:
      - master
  workflow_dispatch: # Allows manual triggering
  pull_request:
    branches:
      - master
    paths:  # Only run on PRs when eviction webhook or cluster-related code or tests change
      - 'internal/webhook/**'
      - 'api/v1/**'
      - 'test/envtests/**'
      - 'test/envtests/cluster/**'
      - '.github/workflows/webhook-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - name: Setup-go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod

      # Install Ginkgo CLI (so `go run` not needed)
      - name: Install Ginkgo CLI
        run: go install github.com/onsi/ginkgo/v2/ginkgo@latest

      # Run your env-test target
      - name: Run EnvTest Suite
        run: make env-test

      # Run cluster webhook envtests
      - name: Run EnvTest Cluster (cluster webhook envtests)
        run: make env-test-cluster